return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter.configs").setup({
			ensure_installed = {
				"bash",
				"zig",
				"c",
				"cpp",
				"rust",
				"nim",
				"python",
				"lua",
				"javascript",
				"typescript",
				"tsx",
				"svelte",
				"html",
				"css",
				"json",
				"jsonc",
				"toml",
				"yaml",
				"vim",
				"gitignore",
				"markdown",
			},
			sync_install = false,
			auto_install = true,
			indent = { enable = true },
			highlight = {
				enable = true,
				additional_vim_regex_highlighting = false,
			},
			modules = {},
			ignore_install = {},
		})
	end,
}
